version: '1'
services:
  math-service:
    build: <path>
    container_name: <image name>

  string-service:
    build: <path>
    container_name: <image name> 

  gateway:
    build: <path>
    container_name: <image name>
    ports:
      - <port>:<port>
    depends_on:
      - math-service
      - string-service
