version: "1"
services:
  math-service:
    build: ./math_py
    container_name: math-container

  string-service:
    build: ./string_py
    container_name: string-container

  gateway:
    build: ./gateway
    container_name: gateway-container
    ports:
      - 8082:8082
    depends_on:
      - math-service
      - string-service
